name: Lint yaml files

on: [push]

jobs:
  lint:
    name: Lint & Fix yaml files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout consumer-sirh
        uses: actions/checkout@v2
      - name: Check yaml files
        uses: opt-nc/yamlfixer-action@v1.0.0
        with:
          yaml_file: .github/workflows
          options: --verbose
          user: ${{secrets.OPT_CI_LOGIN}}
          token: ${{secrets.OPT_CI_TOKEN}}
