name: Lint yaml files

on: [push]

jobs:
  lint:
    name: Lint & Fix yaml files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout consumer-sirh
        uses: actions/checkout@v2
      - name: Check yaml files
        uses: opt-nc/yamlfixer-action@v1.0.1
        with:
          yaml_file: .github/workflows/*.yml
          options: --verbose
          user: ${{github.actor}}
          token: ${{github.token}}
